/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PeerClient;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.HashSet;
import Peer.Peer ;
import Peer.Constants ;

/**
 *
 * @author aayushshivam7
 */
public class userProfile extends javax.swing.JPanel {

    /**
     * Creates new form userProfile
     */
    private Peer peer;
    private PlayingWindow window;

    public userProfile(String username, Peer peer) {
        initComponents();
        welcomeText.setText("Welcome " + username + " !!!!  ,,,, have fun");
        this.peer = peer;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeText = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        watchNow = new javax.swing.JButton();
        searchText = new javax.swing.JTextField();
        createNewChannel = new javax.swing.JButton();
        newChannelName = new javax.swing.JTextField();

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Channels");

        watchNow.setText("Watch Now");
        watchNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchNowActionPerformed(evt);
            }
        });

        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        createNewChannel.setText("Create New Channel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboBox, 0, 168, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(newChannelName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchText)
                    .addComponent(watchNow, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(createNewChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watchNow))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createNewChannel)
                    .addComponent(newChannelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxActionPerformed

    private void openPlayingWindow() {
        window = new PlayingWindow(peer);
        System.out.println("awesome!!");
        peer.getDesktopPane().add(window);
        window.setVisible(true);
        window.moveToFront();
        peer.setContentPane(peer.getDesktopPane());
    }

    private void watchNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchNowActionPerformed
        String fileName = searchText.getText();
        openPlayingWindow();
        try {
            // add playing window to mainframe
            Socket socket = new Socket("localhost", 5050);

            System.out.println(socket);
            BufferedReader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            PrintWriter writer = new PrintWriter(new OutputStreamWriter(socket.getOutputStream()));
            writer.println("SEARCH");
            writer.println(fileName);
            writer.flush();
//            System.out.println("tate");
            String line = reader.readLine();
            HashSet<String> paths = new HashSet<>() ;
            if (line.equals("RESULT")) {
                String co = reader.readLine() ;
                Integer count = Integer.parseInt(co);
                System.out.println(count);
                for (int i = 1; i <= count; i++) {
                    System.out.println(reader.readLine()) ;
                    paths.add(reader.readLine());
                }
                for(String s:paths){
                    writer.println("SETUP");
                    writer.flush() ;
                    writer.println(s) ;
                    writer.flush() ;
                    break ;
                }
                writer.println(Constants.VLC_UDP_PORT);
                writer.flush();
                VlcController vlc = new VlcController() ;
                writer.println("PLAY") ;
                
                writer.flush() ;
            } else {
                // wrong response .... show nothing
            }

        } catch (IOException ex) {
        }
    }//GEN-LAST:event_watchNowActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JButton createNewChannel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField newChannelName;
    private javax.swing.JTextField searchText;
    private javax.swing.JButton watchNow;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
